name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          cd backend
          source venv/bin/activate
          pytest tests/

      - name: Install Render CLI
        run: |
          curl -fsSL https://cdn.render.com/cli/install.sh | bash

      - name: Deploy to Render via CLI
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render deploy service --service-id ${{ secrets.RENDER_SERVICE_ID }}
